export interface Player {
  rank: number;
  name: string;
  team: string;
  position: string;
  price: number;
  bye: number;
}

const players: Player[] = [
  {
    rank: 1,
    name: "Christian McCaffrey",
    team: "SF",
    position: "RB1",
    price: 57,
    bye: 9,
  },
  {
    rank: 2,
    name: "Breece Hall",
    team: "NYJ",
    position: "RB2",
    price: 56,
    bye: 12,
  },
  {
    rank: 3,
    name: "Bijan Robinson",
    team: "ATL",
    position: "RB3",
    price: 55,
    bye: 12,
  },
  {
    rank: 4,
    name: "CeeDee Lamb",
    team: "DAL",
    position: "WR1",
    price: 55,
    bye: 7,
  },
  {
    rank: 5,
    name: "Tyreek Hill",
    team: "MIA",
    position: "WR2",
    price: 54,
    bye: 6,
  },
  {
    rank: 6,
    name: "Ja'Marr Chase",
    team: "CIN",
    position: "WR3",
    price: 53,
    bye: 12,
  },
  {
    rank: 7,
    name: "Amon-Ra St. Brown",
    team: "DET",
    position: "WR4",
    price: 53,
    bye: 5,
  },
  {
    rank: 8,
    name: "Justin Jefferson",
    team: "MIN",
    position: "WR5",
    price: 52,
    bye: 6,
  },
  {
    rank: 9,
    name: "Jonathan Taylor",
    team: "IND",
    position: "RB4",
    price: 51,
    bye: 14,
  },
  {
    rank: 10,
    name: "Saquon Barkley",
    team: "PHI",
    position: "RB5",
    price: 50,
    bye: 5,
  },
  {
    rank: 11,
    name: "A.J. Brown",
    team: "PHI",
    position: "WR6",
    price: 48,
    bye: 5,
  },
  {
    rank: 12,
    name: "Puka Nacua",
    team: "LAR",
    position: "WR7",
    price: 46,
    bye: 6,
  },
  {
    rank: 13,
    name: "Garrett Wilson",
    team: "NYJ",
    position: "WR8",
    price: 45,
    bye: 12,
  },
  {
    rank: 14,
    name: "Jahmyr Gibbs",
    team: "DET",
    position: "RB6",
    price: 43,
    bye: 5,
  },
  {
    rank: 15,
    name: "Kyren Williams",
    team: "LAR",
    position: "RB7",
    price: 42,
    bye: 6,
  },
  {
    rank: 16,
    name: "Isiah Pacheco",
    team: "KC",
    position: "RB8",
    price: 40,
    bye: 6,
  },
  {
    rank: 17,
    name: "Travis Etienne Jr.",
    team: "JAC",
    position: "RB9",
    price: 38,
    bye: 12,
  },
  {
    rank: 18,
    name: "Chris Olave",
    team: "NO",
    position: "WR9",
    price: 37,
    bye: 12,
  },
  {
    rank: 19,
    name: "Davante Adams",
    team: "LV",
    position: "WR10",
    price: 36,
    bye: 10,
  },
  {
    rank: 20,
    name: "Michael Pittman Jr.",
    team: "IND",
    position: "WR11",
    price: 35,
    bye: 14,
  },
  {
    rank: 21,
    name: "Mike Evans",
    team: "TB",
    position: "WR12",
    price: 34,
    bye: 11,
  },
  {
    rank: 22,
    name: "Marvin Harrison Jr.",
    team: "ARI",
    position: "WR13",
    price: 33,
    bye: 11,
  },
  {
    rank: 23,
    name: "Drake London",
    team: "ATL",
    position: "WR14",
    price: 32,
    bye: 12,
  },
  {
    rank: 24,
    name: "Derrick Henry",
    team: "BAL",
    position: "RB10",
    price: 32,
    bye: 14,
  },
  {
    rank: 25,
    name: "Rachaad White",
    team: "TB",
    position: "RB11",
    price: 31,
    bye: 11,
  },
  {
    rank: 26,
    name: "Nico Collins",
    team: "HOU",
    position: "WR15",
    price: 30,
    bye: 14,
  },
  {
    rank: 27,
    name: "DK Metcalf",
    team: "SEA",
    position: "WR16",
    price: 30,
    bye: 10,
  },
  {
    rank: 28,
    name: "Alvin Kamara",
    team: "NO",
    position: "RB12",
    price: 29,
    bye: 12,
  },
  {
    rank: 29,
    name: "James Cook",
    team: "BUF",
    position: "RB13",
    price: 28,
    bye: 12,
  },
  {
    rank: 30,
    name: "Joe Mixon",
    team: "HOU",
    position: "RB14",
    price: 27,
    bye: 14,
  },
  {
    rank: 31,
    name: "Brandon Aiyuk",
    team: "SF",
    position: "WR17",
    price: 26,
    bye: 9,
  },
  {
    rank: 32,
    name: "Deebo Samuel Sr.",
    team: "SF",
    position: "WR18",
    price: 25,
    bye: 9,
  },
  {
    rank: 33,
    name: "DJ Moore",
    team: "CHI",
    position: "WR19",
    price: 24,
    bye: 7,
  },
  {
    rank: 34,
    name: "Stefon Diggs",
    team: "HOU",
    position: "WR20",
    price: 23,
    bye: 14,
  },
  {
    rank: 35,
    name: "Josh Allen",
    team: "BUF",
    position: "QB1",
    price: 22,
    bye: 12,
  },
  {
    rank: 36,
    name: "Sam LaPorta",
    team: "DET",
    position: "TE1",
    price: 22,
    bye: 5,
  },
  {
    rank: 37,
    name: "Travis Kelce",
    team: "KC",
    position: "TE2",
    price: 22,
    bye: 6,
  },
  {
    rank: 38,
    name: "Jalen Hurts",
    team: "PHI",
    position: "QB2",
    price: 21,
    bye: 5,
  },
  {
    rank: 39,
    name: "Josh Jacobs",
    team: "GB",
    position: "RB15",
    price: 21,
    bye: 10,
  },
  {
    rank: 40,
    name: "Kenneth Walker III",
    team: "SEA",
    position: "RB16",
    price: 20,
    bye: 10,
  },
  {
    rank: 41,
    name: "De'Von Achane",
    team: "MIA",
    position: "RB17",
    price: 19,
    bye: 6,
  },
  {
    rank: 42,
    name: "DeVonta Smith",
    team: "PHI",
    position: "WR21",
    price: 19,
    bye: 5,
  },
  {
    rank: 43,
    name: "Jaylen Waddle",
    team: "MIA",
    position: "WR22",
    price: 18,
    bye: 6,
  },
  {
    rank: 44,
    name: "Cooper Kupp",
    team: "LAR",
    position: "WR23",
    price: 17,
    bye: 6,
  },
  {
    rank: 45,
    name: "Zay Flowers",
    team: "BAL",
    position: "WR24",
    price: 17,
    bye: 14,
  },
  {
    rank: 46,
    name: "Calvin Ridley",
    team: "TEN",
    position: "WR25",
    price: 15,
    bye: 5,
  },
  {
    rank: 47,
    name: "Malik Nabers",
    team: "NYG",
    position: "WR26",
    price: 15,
    bye: 11,
  },
  {
    rank: 48,
    name: "Tee Higgins",
    team: "CIN",
    position: "WR27",
    price: 14,
    bye: 12,
  },
  {
    rank: 49,
    name: "Lamar Jackson",
    team: "BAL",
    position: "QB3",
    price: 13,
    bye: 14,
  },
  {
    rank: 50,
    name: "Patrick Mahomes",
    team: "KC",
    position: "QB4",
    price: 13,
    bye: 6,
  },
  {
    rank: 51,
    name: "Mark Andrews",
    team: "BAL",
    position: "TE3",
    price: 12,
    bye: 14,
  },
  {
    rank: 52,
    name: "George Pickens",
    team: "PIT",
    position: "WR28",
    price: 11,
    bye: 9,
  },
  {
    rank: 53,
    name: "Chris Godwin",
    team: "TB",
    position: "WR29",
    price: 11,
    bye: 11,
  },
  {
    rank: 54,
    name: "Tank Dell",
    team: "HOU",
    position: "WR30",
    price: 10,
    bye: 14,
  },
  {
    rank: 55,
    name: "Amari Cooper",
    team: "CLE",
    position: "WR31",
    price: 10,
    bye: 10,
  },
  {
    rank: 56,
    name: "Trey McBride",
    team: "ARI",
    position: "TE4",
    price: 10,
    bye: 11,
  },
  {
    rank: 57,
    name: "Evan Engram",
    team: "JAC",
    position: "TE5",
    price: 10,
    bye: 12,
  },
  {
    rank: 58,
    name: "Anthony Richardson",
    team: "IND",
    position: "QB5",
    price: 9,
    bye: 14,
  },
  {
    rank: 59,
    name: "C.J. Stroud",
    team: "HOU",
    position: "QB6",
    price: 9,
    bye: 14,
  },
  {
    rank: 60,
    name: "Joe Burrow",
    team: "CIN",
    position: "QB7",
    price: 9,
    bye: 12,
  },
  {
    rank: 61,
    name: "Dak Prescott",
    team: "DAL",
    position: "QB8",
    price: 8,
    bye: 7,
  },
  {
    rank: 62,
    name: "Rhamondre Stevenson",
    team: "NE",
    position: "RB18",
    price: 8,
    bye: 14,
  },
  {
    rank: 63,
    name: "D'Andre Swift",
    team: "CHI",
    position: "RB19",
    price: 8,
    bye: 7,
  },
  {
    rank: 64,
    name: "James Conner",
    team: "ARI",
    position: "RB20",
    price: 7,
    bye: 11,
  },
  {
    rank: 65,
    name: "Aaron Jones",
    team: "MIN",
    position: "RB21",
    price: 7,
    bye: 6,
  },
  {
    rank: 66,
    name: "Zamir White",
    team: "LV",
    position: "RB22",
    price: 7,
    bye: 10,
  },
  {
    rank: 67,
    name: "Diontae Johnson",
    team: "CAR",
    position: "WR32",
    price: 7,
    bye: 11,
  },
  {
    rank: 68,
    name: "Keenan Allen",
    team: "CHI",
    position: "WR33",
    price: 6,
    bye: 7,
  },
  {
    rank: 69,
    name: "Rashee Rice",
    team: "KC",
    position: "WR34",
    price: 6,
    bye: 6,
  },
  {
    rank: 70,
    name: "Christian Kirk",
    team: "JAC",
    position: "WR35",
    price: 6,
    bye: 12,
  },
  {
    rank: 71,
    name: "DeAndre Hopkins",
    team: "TEN",
    position: "WR36",
    price: 6,
    bye: 5,
  },
  {
    rank: 72,
    name: "Terry McLaurin",
    team: "WAS",
    position: "WR37",
    price: 6,
    bye: 14,
  },
  {
    rank: 73,
    name: "George Kittle",
    team: "SF",
    position: "TE6",
    price: 6,
    bye: 9,
  },
  {
    rank: 74,
    name: "Dalton Kincaid",
    team: "BUF",
    position: "TE7",
    price: 5,
    bye: 12,
  },
  {
    rank: 75,
    name: "Kyle Pitts",
    team: "ATL",
    position: "TE8",
    price: 5,
    bye: 12,
  },
  {
    rank: 76,
    name: "Brian Robinson Jr.",
    team: "WAS",
    position: "RB23",
    price: 5,
    bye: 14,
  },
  {
    rank: 77,
    name: "Jonathon Brooks",
    team: "CAR",
    position: "RB24",
    price: 5,
    bye: 11,
  },
  {
    rank: 78,
    name: "Najee Harris",
    team: "PIT",
    position: "RB25",
    price: 4,
    bye: 9,
  },
  {
    rank: 79,
    name: "David Montgomery",
    team: "DET",
    position: "RB26",
    price: 4,
    bye: 5,
  },
  {
    rank: 80,
    name: "Jaylen Warren",
    team: "PIT",
    position: "RB27",
    price: 4,
    bye: 9,
  },
  {
    rank: 81,
    name: "Jaxon Smith-Njigba",
    team: "SEA",
    position: "WR38",
    price: 4,
    bye: 10,
  },
  {
    rank: 82,
    name: "Jordan Addison",
    team: "MIN",
    position: "WR39",
    price: 4,
    bye: 6,
  },
  {
    rank: 83,
    name: "Courtland Sutton",
    team: "DEN",
    position: "WR40",
    price: 4,
    bye: 14,
  },
  {
    rank: 84,
    name: "Christian Watson",
    team: "GB",
    position: "WR41",
    price: 4,
    bye: 10,
  },
  {
    rank: 85,
    name: "Jayden Reed",
    team: "GB",
    position: "WR42",
    price: 4,
    bye: 10,
  },
  {
    rank: 86,
    name: "Marquise Brown",
    team: "KC",
    position: "WR43",
    price: 4,
    bye: 6,
  },
  {
    rank: 87,
    name: "Javonte Williams",
    team: "DEN",
    position: "RB28",
    price: 3,
    bye: 14,
  },
  {
    rank: 88,
    name: "Tyjae Spears",
    team: "TEN",
    position: "RB29",
    price: 3,
    bye: 5,
  },
  {
    rank: 89,
    name: "Tony Pollard",
    team: "TEN",
    position: "RB30",
    price: 3,
    bye: 5,
  },
  {
    rank: 90,
    name: "Austin Ekeler",
    team: "WAS",
    position: "RB31",
    price: 3,
    bye: 14,
  },
  {
    rank: 91,
    name: "Kyler Murray",
    team: "ARI",
    position: "QB9",
    price: 3,
    bye: 11,
  },
  {
    rank: 92,
    name: "Jordan Love",
    team: "GB",
    position: "QB10",
    price: 3,
    bye: 10,
  },
  {
    rank: 93,
    name: "Brock Purdy",
    team: "SF",
    position: "QB11",
    price: 3,
    bye: 9,
  },
  {
    rank: 94,
    name: "Rome Odunze",
    team: "CHI",
    position: "WR44",
    price: 3,
    bye: 7,
  },
  {
    rank: 95,
    name: "Xavier Worthy",
    team: "KC",
    position: "WR45",
    price: 3,
    bye: 6,
  },
  {
    rank: 96,
    name: "Ladd McConkey",
    team: "LAC",
    position: "WR46",
    price: 2,
    bye: 5,
  },
  {
    rank: 97,
    name: "Keon Coleman",
    team: "BUF",
    position: "WR47",
    price: 2,
    bye: 12,
  },
  {
    rank: 98,
    name: "Brian Thomas Jr.",
    team: "JAC",
    position: "WR48",
    price: 2,
    bye: 12,
  },
  {
    rank: 99,
    name: "Jayden Daniels",
    team: "WAS",
    position: "QB12",
    price: 2,
    bye: 14,
  },
  {
    rank: 100,
    name: "David Njoku",
    team: "CLE",
    position: "TE9",
    price: 2,
    bye: 10,
  },
  {
    rank: 101,
    name: "Jake Ferguson",
    team: "DAL",
    position: "TE10",
    price: 2,
    bye: 7,
  },
  {
    rank: 102,
    name: "Devin Singletary",
    team: "NYG",
    position: "RB32",
    price: 2,
    bye: 11,
  },
  {
    rank: 103,
    name: "Ezekiel Elliott",
    team: "DAL",
    position: "RB33",
    price: 2,
    bye: 7,
  },
  {
    rank: 104,
    name: "Raheem Mostert",
    team: "MIA",
    position: "RB34",
    price: 2,
    bye: 6,
  },
  {
    rank: 105,
    name: "Zack Moss",
    team: "CIN",
    position: "RB35",
    price: 2,
    bye: 12,
  },
  {
    rank: 106,
    name: "Chase Brown",
    team: "CIN",
    position: "RB36",
    price: 2,
    bye: 12,
  },
  {
    rank: 107,
    name: "Jakobi Meyers",
    team: "LV",
    position: "WR49",
    price: 2,
    bye: 10,
  },
  {
    rank: 108,
    name: "Mike Williams",
    team: "NYJ",
    position: "WR50",
    price: 2,
    bye: 12,
  },
  {
    rank: 109,
    name: "Tyler Lockett",
    team: "SEA",
    position: "WR51",
    price: 2,
    bye: 10,
  },
  {
    rank: 110,
    name: "Dallas Goedert",
    team: "PHI",
    position: "TE11",
    price: 2,
    bye: 5,
  },
  {
    rank: 111,
    name: "Brock Bowers",
    team: "LV",
    position: "TE12",
    price: 2,
    bye: 10,
  },
  {
    rank: 112,
    name: "T.J. Hockenson",
    team: "MIN",
    position: "TE13",
    price: 2,
    bye: 6,
  },
  {
    rank: 113,
    name: "J.K. Dobbins",
    team: "LAC",
    position: "RB37",
    price: 2,
    bye: 5,
  },
  {
    rank: 114,
    name: "Gus Edwards",
    team: "LAC",
    position: "RB38",
    price: 2,
    bye: 5,
  },
  {
    rank: 115,
    name: "Nick Chubb",
    team: "CLE",
    position: "RB39",
    price: 2,
    bye: 10,
  },
  {
    rank: 116,
    name: "Jerome Ford",
    team: "CLE",
    position: "RB40",
    price: 2,
    bye: 10,
  },
  {
    rank: 117,
    name: "Chuba Hubbard",
    team: "CAR",
    position: "RB41",
    price: 2,
    bye: 11,
  },
  {
    rank: 118,
    name: "Aaron Rodgers",
    team: "NYJ",
    position: "QB13",
    price: 2,
    bye: 12,
  },
  {
    rank: 119,
    name: "Justin Herbert",
    team: "LAC",
    position: "QB14",
    price: 2,
    bye: 5,
  },
  {
    rank: 120,
    name: "Kirk Cousins",
    team: "ATL",
    position: "QB15",
    price: 2,
    bye: 12,
  },
  {
    rank: 121,
    name: "Zach Charbonnet",
    team: "SEA",
    position: "RB42",
    price: 1,
    bye: 10,
  },
  {
    rank: 122,
    name: "Tyler Allgeier",
    team: "ATL",
    position: "RB43",
    price: 1,
    bye: 12,
  },
  {
    rank: 123,
    name: "Ty Chandler",
    team: "MIN",
    position: "RB44",
    price: 1,
    bye: 6,
  },
  {
    rank: 124,
    name: "Trey Benson",
    team: "ARI",
    position: "RB45",
    price: 1,
    bye: 11,
  },
  {
    rank: 125,
    name: "Darnell Mooney",
    team: "ATL",
    position: "WR52",
    price: 1,
    bye: 12,
  },
  {
    rank: 126,
    name: "Jerry Jeudy",
    team: "CLE",
    position: "WR53",
    price: 1,
    bye: 10,
  },
  {
    rank: 127,
    name: "Gabe Davis",
    team: "JAC",
    position: "WR54",
    price: 1,
    bye: 12,
  },
  {
    rank: 128,
    name: "Adam Thielen",
    team: "CAR",
    position: "WR55",
    price: 1,
    bye: 11,
  },
  {
    rank: 129,
    name: "Curtis Samuel",
    team: "BUF",
    position: "WR56",
    price: 1,
    bye: 12,
  },
  {
    rank: 130,
    name: "Jameson Williams",
    team: "DET",
    position: "WR57",
    price: 1,
    bye: 5,
  },
  {
    rank: 131,
    name: "Rashid Shaheed",
    team: "NO",
    position: "WR58",
    price: 1,
    bye: 12,
  },
  {
    rank: 132,
    name: "Caleb Williams",
    team: "CHI",
    position: "QB16",
    price: 1,
    bye: 7,
  },
  {
    rank: 133,
    name: "Deshaun Watson",
    team: "CLE",
    position: "QB17",
    price: 1,
    bye: 10,
  },
  {
    rank: 134,
    name: "Trevor Lawrence",
    team: "JAC",
    position: "QB18",
    price: 1,
    bye: 12,
  },
  {
    rank: 135,
    name: "Pat Freiermuth",
    team: "PIT",
    position: "TE14",
    price: 1,
    bye: 9,
  },
  {
    rank: 136,
    name: "Cole Kmet",
    team: "CHI",
    position: "TE15",
    price: 1,
    bye: 7,
  },
  {
    rank: 137,
    name: "Dalton Schultz",
    team: "HOU",
    position: "TE16",
    price: 1,
    bye: 14,
  },
  {
    rank: 138,
    name: "DeMario Douglas",
    team: "NE",
    position: "WR59",
    price: 1,
    bye: 14,
  },
  {
    rank: 139,
    name: "Khalil Shakir",
    team: "BUF",
    position: "WR60",
    price: 1,
    bye: 12,
  },
  {
    rank: 140,
    name: "Ja'Lynn Polk",
    team: "NE",
    position: "WR61",
    price: 1,
    bye: 14,
  },
  {
    rank: 141,
    name: "Adonai Mitchell",
    team: "IND",
    position: "WR62",
    price: 1,
    bye: 14,
  },
  {
    rank: 142,
    name: "Antonio Gibson",
    team: "NE",
    position: "RB46",
    price: 1,
    bye: 14,
  },
  {
    rank: 143,
    name: "Blake Corum",
    team: "LAR",
    position: "RB47",
    price: 1,
    bye: 6,
  },
  {
    rank: 144,
    name: "Kendre Miller",
    team: "NO",
    position: "RB48",
    price: 1,
    bye: 12,
  },
  {
    rank: 145,
    name: "MarShawn Lloyd",
    team: "GB",
    position: "RB49",
    price: 1,
    bye: 10,
  },
  {
    rank: 146,
    name: "Jaleel McLaughlin",
    team: "DEN",
    position: "RB50",
    price: 1,
    bye: 14,
  },
  {
    rank: 147,
    name: "Xavier Legette",
    team: "CAR",
    position: "WR63",
    price: 1,
    bye: 11,
  },
  {
    rank: 148,
    name: "Joshua Palmer",
    team: "LAC",
    position: "WR64",
    price: 1,
    bye: 5,
  },
  {
    rank: 149,
    name: "Kendrick Bourne",
    team: "NE",
    position: "WR65",
    price: 1,
    bye: 14,
  },
  {
    rank: 150,
    name: "Marvin Mims Jr.",
    team: "DEN",
    position: "WR66",
    price: 1,
    bye: 14,
  },
  {
    rank: 151,
    name: "Romeo Doubs",
    team: "GB",
    position: "WR67",
    price: 1,
    bye: 10,
  },
  {
    rank: 152,
    name: "Dontayvion Wicks",
    team: "GB",
    position: "WR68",
    price: 1,
    bye: 10,
  },
  {
    rank: 153,
    name: "Rico Dowdle",
    team: "DAL",
    position: "RB51",
    price: 1,
    bye: 7,
  },
  {
    rank: 154,
    name: "Miles Sanders",
    team: "CAR",
    position: "RB52",
    price: 1,
    bye: 11,
  },
  {
    rank: 155,
    name: "Khalil Herbert",
    team: "CHI",
    position: "RB53",
    price: 1,
    bye: 7,
  },
  {
    rank: 156,
    name: "Ray Davis",
    team: "BUF",
    position: "RB54",
    price: 1,
    bye: 12,
  },
  {
    rank: 157,
    name: "Jaylen Wright",
    team: "MIA",
    position: "RB55",
    price: 1,
    bye: 6,
  },
  {
    rank: 158,
    name: "Alexander Mattison",
    team: "LV",
    position: "RB56",
    price: 1,
    bye: 10,
  },
  {
    rank: 159,
    name: "Elijah Mitchell",
    team: "SF",
    position: "RB57",
    price: 1,
    bye: 9,
  },
  {
    rank: 160,
    name: "Brandin Cooks",
    team: "DAL",
    position: "WR69",
    price: 1,
    bye: 7,
  },
  {
    rank: 161,
    name: "Josh Downs",
    team: "IND",
    position: "WR70",
    price: 0,
    bye: 14,
  },
  {
    rank: 162,
    name: "Ricky Pearsall",
    team: "SF",
    position: "WR71",
    price: 0,
    bye: 9,
  },
  {
    rank: 163,
    name: "Tua Tagovailoa",
    team: "MIA",
    position: "QB19",
    price: 0,
    bye: 6,
  },
  {
    rank: 164,
    name: "Jared Goff",
    team: "DET",
    position: "QB20",
    price: 0,
    bye: 5,
  },
  {
    rank: 165,
    name: "Tyler Conklin",
    team: "NYJ",
    position: "TE17",
    price: 0,
    bye: 12,
  },
  {
    rank: 166,
    name: "Taysom Hill",
    team: "NO",
    position: "TE18",
    price: 0,
    bye: 12,
  },
  {
    rank: 167,
    name: "Chigoziem Okonkwo",
    team: "TEN",
    position: "TE19",
    price: 0,
    bye: 5,
  },
  {
    rank: 168,
    name: "Hunter Henry",
    team: "NE",
    position: "TE20",
    price: 0,
    bye: 14,
  },
  {
    rank: 169,
    name: "Browns D/ST",
    team: "CLE",
    position: "DST1",
    price: 0,
    bye: 10,
  },
  {
    rank: 170,
    name: "Cowboys D/ST",
    team: "DAL",
    position: "DST2",
    price: 0,
    bye: 7,
  },
  {
    rank: 171,
    name: "Jets D/ST",
    team: "NYJ",
    position: "DST3",
    price: 0,
    bye: 12,
  },
  {
    rank: 172,
    name: "Ravens D/ST",
    team: "BAL",
    position: "DST4",
    price: 0,
    bye: 14,
  },
  {
    rank: 173,
    name: "49ers D/ST",
    team: "SF",
    position: "DST5",
    price: 0,
    bye: 9,
  },
  {
    rank: 174,
    name: "Steelers D/ST",
    team: "PIT",
    position: "DST6",
    price: 0,
    bye: 9,
  },
  {
    rank: 175,
    name: "Dolphins D/ST",
    team: "MIA",
    position: "DST7",
    price: 0,
    bye: 6,
  },
  {
    rank: 176,
    name: "Jaguars D/ST",
    team: "JAC",
    position: "DST8",
    price: 0,
    bye: 12,
  },
  {
    rank: 177,
    name: "Saints D/ST",
    team: "NO",
    position: "DST9",
    price: 0,
    bye: 12,
  },
  {
    rank: 178,
    name: "Bengals D/ST",
    team: "CIN",
    position: "DST10",
    price: 0,
    bye: 12,
  },
  {
    rank: 179,
    name: "Chiefs D/ST",
    team: "KC",
    position: "DST11",
    price: 0,
    bye: 6,
  },
  {
    rank: 180,
    name: "Lions D/ST",
    team: "DET",
    position: "DST12",
    price: 0,
    bye: 5,
  },
  {
    rank: 181,
    name: "Harrison Butker",
    team: "KC",
    position: "K1",
    price: 0,
    bye: 6,
  },
  {
    rank: 182,
    name: "Brandon Aubrey",
    team: "DAL",
    position: "K2",
    price: 0,
    bye: 7,
  },
  {
    rank: 183,
    name: "Justin Tucker",
    team: "BAL",
    position: "K3",
    price: 0,
    bye: 14,
  },
  {
    rank: 184,
    name: "Jake Elliott",
    team: "PHI",
    position: "K4",
    price: 0,
    bye: 5,
  },
  {
    rank: 185,
    name: "Greg Zuerlein",
    team: "NYJ",
    position: "K5",
    price: 0,
    bye: 12,
  },
  {
    rank: 186,
    name: "Ka'imi Fairbairn",
    team: "HOU",
    position: "K6",
    price: 0,
    bye: 14,
  },
  {
    rank: 187,
    name: "Evan McPherson",
    team: "CIN",
    position: "K7",
    price: 0,
    bye: 12,
  },
  {
    rank: 188,
    name: "Jake Moody",
    team: "SF",
    position: "K8",
    price: 0,
    bye: 9,
  },
  {
    rank: 189,
    name: "Cameron Dicker",
    team: "LAC",
    position: "K9",
    price: 0,
    bye: 5,
  },
  {
    rank: 190,
    name: "Cairo Santos",
    team: "CHI",
    position: "K10",
    price: 0,
    bye: 7,
  },
  {
    rank: 191,
    name: "Younghoe Koo",
    team: "ATL",
    position: "K11",
    price: 0,
    bye: 12,
  },
  {
    rank: 192,
    name: "Jake Bates",
    team: "DET",
    position: "K12",
    price: 0,
    bye: 5,
  },
  {
    rank: 193,
    name: "Juwan Johnson",
    team: "NO",
    position: "TE21",
    price: 0,
    bye: 12,
  },
  {
    rank: 194,
    name: "Quentin Johnston",
    team: "LAC",
    position: "WR72",
    price: 0,
    bye: 5,
  },
  {
    rank: 195,
    name: "Clyde Edwards-Helaire",
    team: "KC",
    position: "RB58",
    price: 0,
    bye: 6,
  },
  {
    rank: 196,
    name: "Braelon Allen",
    team: "NYJ",
    position: "RB59",
    price: 0,
    bye: 12,
  },
  {
    rank: 197,
    name: "Matthew Stafford",
    team: "LAR",
    position: "QB21",
    price: 0,
    bye: 6,
  },
  {
    rank: 198,
    name: "Bryce Young",
    team: "CAR",
    position: "QB22",
    price: 0,
    bye: 11,
  },
  {
    rank: 199,
    name: "Daniel Jones",
    team: "NYG",
    position: "QB23",
    price: 0,
    bye: 11,
  },
  {
    rank: 200,
    name: "Baker Mayfield",
    team: "TB",
    position: "QB24",
    price: 0,
    bye: 11,
  },
  {
    rank: 201,
    name: "Demarcus Robinson",
    team: "LAR",
    position: "WR73",
    price: 0,
    bye: 6,
  },
  {
    rank: 202,
    name: "Wan'Dale Robinson",
    team: "NYG",
    position: "WR74",
    price: 0,
    bye: 11,
  },
  {
    rank: 203,
    name: "Tyler Boyd",
    team: "TEN",
    position: "WR75",
    price: 0,
    bye: 5,
  },
  {
    rank: 204,
    name: "Darius Slayton",
    team: "NYG",
    position: "WR76",
    price: 0,
    bye: 11,
  },
  {
    rank: 205,
    name: "Jalin Hyatt",
    team: "NYG",
    position: "WR77",
    price: 0,
    bye: 11,
  },
  {
    rank: 206,
    name: "Tucker Kraft",
    team: "GB",
    position: "TE22",
    price: 0,
    bye: 10,
  },
  {
    rank: 207,
    name: "Luke Musgrave",
    team: "GB",
    position: "TE23",
    price: 0,
    bye: 10,
  },
  {
    rank: 208,
    name: "Jahan Dotson",
    team: "WAS",
    position: "WR78",
    price: 0,
    bye: 14,
  },
  {
    rank: 209,
    name: "Jermaine Burton",
    team: "CIN",
    position: "WR79",
    price: 0,
    bye: 12,
  },
  {
    rank: 210,
    name: "DJ Chark Jr.",
    team: "LAC",
    position: "WR80",
    price: 0,
    bye: 5,
  },
  {
    rank: 211,
    name: "Zay Jones",
    team: "ARI",
    position: "WR81",
    price: 0,
    bye: 11,
  },
  {
    rank: 212,
    name: "Keaton Mitchell",
    team: "BAL",
    position: "RB60",
    price: 0,
    bye: 14,
  },
  {
    rank: 213,
    name: "Jamaal Williams",
    team: "NO",
    position: "RB61",
    price: 0,
    bye: 12,
  },
  {
    rank: 214,
    name: "Tank Bigsby",
    team: "JAC",
    position: "RB62",
    price: 0,
    bye: 12,
  },
  {
    rank: 215,
    name: "Noah Fant",
    team: "SEA",
    position: "TE24",
    price: 0,
    bye: 10,
  },
  {
    rank: 216,
    name: "Cade Otton",
    team: "TB",
    position: "TE25",
    price: 0,
    bye: 11,
  },
  {
    rank: 217,
    name: "Hayden Hurst",
    team: "LAC",
    position: "TE26",
    price: 0,
    bye: 5,
  },
  {
    rank: 218,
    name: "Geno Smith",
    team: "SEA",
    position: "QB25",
    price: 0,
    bye: 10,
  },
  {
    rank: 219,
    name: "Will Levis",
    team: "TEN",
    position: "QB26",
    price: 0,
    bye: 5,
  },
  {
    rank: 220,
    name: "Russell Wilson",
    team: "PIT",
    position: "QB27",
    price: 0,
    bye: 9,
  },
  {
    rank: 221,
    name: "Kenneth Gainwell",
    team: "PHI",
    position: "RB63",
    price: 0,
    bye: 5,
  },
  {
    rank: 222,
    name: "Roschon Johnson",
    team: "CHI",
    position: "RB64",
    price: 0,
    bye: 7,
  },
  {
    rank: 223,
    name: "Tyrone Tracy Jr.",
    team: "NYG",
    position: "RB65",
    price: 0,
    bye: 11,
  },
  {
    rank: 224,
    name: "Rashod Bateman",
    team: "BAL",
    position: "WR82",
    price: 0,
    bye: 14,
  },
  {
    rank: 225,
    name: "Justice Hill",
    team: "BAL",
    position: "RB66",
    price: 0,
    bye: 14,
  },
  {
    rank: 226,
    name: "Bucky Irving",
    team: "TB",
    position: "RB67",
    price: 0,
    bye: 11,
  },
  {
    rank: 227,
    name: "Jalen Tolbert",
    team: "DAL",
    position: "WR83",
    price: 0,
    bye: 7,
  },
  {
    rank: 228,
    name: "Michael Wilson",
    team: "ARI",
    position: "WR84",
    price: 0,
    bye: 11,
  },
  {
    rank: 229,
    name: "Luke McCaffrey",
    team: "WAS",
    position: "WR85",
    price: 0,
    bye: 14,
  },
  {
    rank: 230,
    name: "Rondale Moore",
    team: "ATL",
    position: "WR86",
    price: 0,
    bye: 12,
  },
  {
    rank: 231,
    name: "Jalen McMillan",
    team: "TB",
    position: "WR87",
    price: 0,
    bye: 11,
  },
  {
    rank: 232,
    name: "Odell Beckham Jr.",
    team: "MIA",
    position: "WR88",
    price: 0,
    bye: 6,
  },
  {
    rank: 233,
    name: "Trey Palmer",
    team: "TB",
    position: "WR89",
    price: 0,
    bye: 11,
  },
  {
    rank: 234,
    name: "Malachi Corley",
    team: "NYJ",
    position: "WR90",
    price: 0,
    bye: 12,
  },
  {
    rank: 235,
    name: "Bears D/ST",
    team: "CHI",
    position: "DST13",
    price: 0,
    bye: 7,
  },
  {
    rank: 236,
    name: "Bills D/ST",
    team: "BUF",
    position: "DST14",
    price: 0,
    bye: 12,
  },
  {
    rank: 237,
    name: "Dustin Hopkins",
    team: "CLE",
    position: "K13",
    price: 0,
    bye: 10,
  },
  {
    rank: 238,
    name: "Matt Gay",
    team: "IND",
    position: "K14",
    price: 0,
    bye: 14,
  },
  {
    rank: 239,
    name: "D'Onta Foreman",
    team: "CLE",
    position: "RB68",
    price: 0,
    bye: 10,
  },
  {
    rank: 240,
    name: "Dameon Pierce",
    team: "HOU",
    position: "RB69",
    price: 0,
    bye: 14,
  },
  {
    rank: 241,
    name: "Ty Johnson",
    team: "BUF",
    position: "RB70",
    price: 0,
    bye: 12,
  },
  {
    rank: 242,
    name: "Audric Estime",
    team: "DEN",
    position: "RB71",
    price: 0,
    bye: 14,
  },
  {
    rank: 243,
    name: "Chase Edmonds",
    team: "TB",
    position: "RB72",
    price: 0,
    bye: 11,
  },
  {
    rank: 244,
    name: "Eric Gray",
    team: "NYG",
    position: "RB73",
    price: 0,
    bye: 11,
  },
  {
    rank: 245,
    name: "Ameer Abdullah",
    team: "LV",
    position: "RB74",
    price: 0,
    bye: 10,
  },
  {
    rank: 246,
    name: "Isaiah Davis",
    team: "NYJ",
    position: "RB75",
    price: 0,
    bye: 12,
  },
  {
    rank: 247,
    name: "Michael Carter",
    team: "ARI",
    position: "RB76",
    price: 0,
    bye: 11,
  },
  {
    rank: 248,
    name: "Nyheim Hines",
    team: "CLE",
    position: "RB77",
    price: 0,
    bye: 10,
  },
  {
    rank: 249,
    name: "Trey Sermon",
    team: "IND",
    position: "RB78",
    price: 0,
    bye: 14,
  },
  {
    rank: 250,
    name: "D'Ernest Johnson",
    team: "JAC",
    position: "RB79",
    price: 0,
    bye: 12,
  },
  {
    rank: 251,
    name: "Deuce Vaughn",
    team: "DAL",
    position: "RB80",
    price: 0,
    bye: 7,
  },
  {
    rank: 252,
    name: "Kalif Raymond",
    team: "DET",
    position: "WR91",
    price: 0,
    bye: 5,
  },
  {
    rank: 253,
    name: "Nelson Agholor",
    team: "BAL",
    position: "WR92",
    price: 0,
    bye: 14,
  },
  {
    rank: 254,
    name: "Colts D/ST",
    team: "IND",
    position: "DST15",
    price: 0,
    bye: 14,
  },
  {
    rank: 255,
    name: "Seahawks D/ST",
    team: "SEA",
    position: "DST16",
    price: 0,
    bye: 10,
  },
  {
    rank: 256,
    name: "Eddy Pineiro",
    team: "CAR",
    position: "K15",
    price: 0,
    bye: 11,
  },
  {
    rank: 257,
    name: "Chase McLaughlin",
    team: "TB",
    position: "K16",
    price: 0,
    bye: 11,
  },
  {
    rank: 258,
    name: "Jonnu Smith",
    team: "MIA",
    position: "TE27",
    price: 0,
    bye: 6,
  },
  {
    rank: 259,
    name: "Dawson Knox",
    team: "BUF",
    position: "TE28",
    price: 0,
    bye: 12,
  },
  {
    rank: 260,
    name: "Jelani Woods",
    team: "IND",
    position: "TE29",
    price: 0,
    bye: 14,
  },
  {
    rank: 261,
    name: "Van Jefferson",
    team: "PIT",
    position: "WR93",
    price: 0,
    bye: 9,
  },
  {
    rank: 262,
    name: "Elijah Moore",
    team: "CLE",
    position: "WR94",
    price: 0,
    bye: 10,
  },
  {
    rank: 263,
    name: "Roman Wilson",
    team: "PIT",
    position: "WR95",
    price: 0,
    bye: 9,
  },
  {
    rank: 264,
    name: "Tim Patrick",
    team: "DEN",
    position: "WR96",
    price: 0,
    bye: 14,
  },
  {
    rank: 265,
    name: "Evan Hull",
    team: "IND",
    position: "RB81",
    price: 0,
    bye: 14,
  },
  {
    rank: 266,
    name: "Trayveon Williams",
    team: "CIN",
    position: "RB82",
    price: 0,
    bye: 12,
  },
  {
    rank: 267,
    name: "Bo Nix",
    team: "DEN",
    position: "QB28",
    price: 0,
    bye: 14,
  },
  {
    rank: 268,
    name: "Derek Carr",
    team: "NO",
    position: "QB29",
    price: 0,
    bye: 12,
  },
  {
    rank: 269,
    name: "J.J. McCarthy",
    team: "MIN",
    position: "QB30",
    price: 0,
    bye: 6,
  },
  {
    rank: 270,
    name: "Drake Maye",
    team: "NE",
    position: "QB31",
    price: 0,
    bye: 14,
  },
  {
    rank: 271,
    name: "Tre Tucker",
    team: "LV",
    position: "WR97",
    price: 0,
    bye: 10,
  },
  {
    rank: 272,
    name: "Cedric Tillman",
    team: "CLE",
    position: "WR98",
    price: 0,
    bye: 10,
  },
  {
    rank: 273,
    name: "Josh Reynolds",
    team: "DEN",
    position: "WR99",
    price: 0,
    bye: 14,
  },
  {
    rank: 274,
    name: "Jonathan Mingo",
    team: "CAR",
    position: "WR100",
    price: 0,
    bye: 11,
  },
  {
    rank: 275,
    name: "KaVontae Turpin",
    team: "DAL",
    position: "WR101",
    price: 0,
    bye: 7,
  },
  {
    rank: 276,
    name: "Chris Rodriguez Jr.",
    team: "WAS",
    position: "RB83",
    price: 0,
    bye: 14,
  },
  {
    rank: 277,
    name: "Kimani Vidal",
    team: "LAC",
    position: "RB84",
    price: 0,
    bye: 5,
  },
  {
    rank: 278,
    name: "Dare Ogunbowale",
    team: "HOU",
    position: "RB85",
    price: 0,
    bye: 14,
  },
  {
    rank: 279,
    name: "Cordarrelle Patterson",
    team: "PIT",
    position: "RB86",
    price: 0,
    bye: 9,
  },
  {
    rank: 280,
    name: "Kenny McIntosh",
    team: "SEA",
    position: "RB87",
    price: 0,
    bye: 10,
  },
  {
    rank: 281,
    name: "Julius Chestnut",
    team: "TEN",
    position: "RB88",
    price: 0,
    bye: 5,
  },
  {
    rank: 282,
    name: "Will Shipley",
    team: "PHI",
    position: "RB89",
    price: 0,
    bye: 5,
  },
  {
    rank: 283,
    name: "Jordan Mason",
    team: "SF",
    position: "RB90",
    price: 0,
    bye: 9,
  },
  {
    rank: 284,
    name: "Andrei Iosivas",
    team: "CIN",
    position: "WR102",
    price: 0,
    bye: 12,
  },
  {
    rank: 285,
    name: "Texans D/ST",
    team: "HOU",
    position: "DST17",
    price: 0,
    bye: 14,
  },
  {
    rank: 286,
    name: "Panthers D/ST",
    team: "CAR",
    position: "DST18",
    price: 0,
    bye: 11,
  },
  {
    rank: 287,
    name: "Jason Sanders",
    team: "MIA",
    position: "K17",
    price: 0,
    bye: 6,
  },
  {
    rank: 288,
    name: "Nick Folk",
    team: "TEN",
    position: "K18",
    price: 0,
    bye: 5,
  },
  {
    rank: 289,
    name: "Ben Sinnott",
    team: "WAS",
    position: "TE30",
    price: 0,
    bye: 14,
  },
  {
    rank: 290,
    name: "Daniel Bellinger",
    team: "NYG",
    position: "TE31",
    price: 0,
    bye: 11,
  },
  {
    rank: 291,
    name: "Colby Parkinson",
    team: "LAR",
    position: "TE32",
    price: 0,
    bye: 6,
  },
  {
    rank: 292,
    name: "Greg Dulcich",
    team: "DEN",
    position: "TE33",
    price: 0,
    bye: 14,
  },
  {
    rank: 293,
    name: "Zach Ertz",
    team: "WAS",
    position: "TE34",
    price: 0,
    bye: 14,
  },
  {
    rank: 294,
    name: "Troy Franklin",
    team: "DEN",
    position: "WR103",
    price: 0,
    bye: 14,
  },
  {
    rank: 295,
    name: "Tutu Atwell",
    team: "LAR",
    position: "WR104",
    price: 0,
    bye: 6,
  },
  {
    rank: 296,
    name: "Gardner Minshew II",
    team: "LV",
    position: "QB32",
    price: 0,
    bye: 10,
  },
  {
    rank: 297,
    name: "Eagles D/ST",
    team: "PHI",
    position: "DST19",
    price: 0,
    bye: 5,
  },
  {
    rank: 298,
    name: "Raiders D/ST",
    team: "LV",
    position: "DST20",
    price: 0,
    bye: 10,
  },
  {
    rank: 299,
    name: "Packers D/ST",
    team: "GB",
    position: "DST21",
    price: 0,
    bye: 10,
  },
  {
    rank: 300,
    name: "Patriots D/ST",
    team: "NE",
    position: "DST22",
    price: 0,
    bye: 14,
  },
];

export default players;
